spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/message?characterEncoding=utf8&useSSL=FALSE
    username: root
    password: 932384

mybatis:
  configuration: # ???? MyBatis ??
    map.underscore-to-camel-case: true # ????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
